_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-arm64
features:
    value:
        - distance_from_net
        - angle_from_net
model_types:
    value:
        - Distance Only
        - Angle Only
        - Distance + Angle
random_state:
    value: 42
test_size:
    value: 0.2
